// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      print("is it well ${web}");
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyDb8z6msk41onj52sgYTdMqkR492sm5Nyk",
      authDomain: "findquiz-d782f.firebaseapp.com",
      projectId: "findquiz-d782f",
      storageBucket: "",
      messagingSenderId: "566827220919",
      appId: "1:566827220919:web:c6aab0b5ba5bb5212ab232",
      measurementId: ""
  );


  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASb4GyB-KZvEprrFN561LxLZq4u73O0YI',
    appId: '1:566827220919:android:8c08f394ee87fb462ab232',
    messagingSenderId: '',
    projectId: 'findquiz-d782f',
    storageBucket: '',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoA_AQ1qLDKC7QCcxoZpGGNKC37XWjNic',
    appId: '1:566827220919:ios:21dee7e7c8f750b72ab232',
    messagingSenderId: '',
    projectId: 'findquiz-d782f',
    storageBucket: '',
    iosClientId: '',
    iosBundleId: 'com.app.findQuiz',
  );
}
